node_js:
  - 13
services:
  - docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests. Yes there will be tests"
script:
  - docker --version # print the version for logging here.
  - docker build -t udagram-reverseproxy:v1 ./udagram-reverseproxy
  - docker build -t udagram-api-feed:v1 ./udagram-api-feed
  - docker build -t udagram-api-user:v1 ./udagram-api-user
  - docker build -t udagram-frontend:local ./udagram-frontend
  # Tagging
  - docker tag udagram-reverseproxy:v1 ifeoh/udagram-reverseproxy:v1
  - docker tag udagram-api-feed:v1 ifeoh/udagram-api-feed:v1
  - docker tag udagram-api-user:v1 ifeoh/udagram-api-user:v1
  - docker tag udagram-frontend:local ifeoh/udagram-frontend:local
# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ifeoh/udagram-reverseproxy:v1
  - docker push ifeoh/udagram-api-feed:v1
  - docker push ifeoh/udagram-api-user:v1
  - docker push ifeoh/udagram-frontend:local
